# dev.yml

# Development Environment Settings
environment: development
debug: true
logging_level: debug

# Database Configuration
database:
  host: localhost
  port: 5432
  username: dev_user
  password: dev_password
  database_name: dev_database

# API Configuration
api:
  base_url: http://localhost:3000/api
  timeout: 5000

# Feature Flags
features:
  enable_feature_1: true
  enable_feature_2: false

